# Generated by Django 4.1.3 on 2022-11-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Disease Name')),
                ('description', models.TextField(max_length=250, verbose_name='Disease Description')),
                ('symptoms', models.TextField(max_length=150, verbose_name='Main Symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.TextField(max_length=250, verbose_name='Tests Performed')),
                ('fees', models.IntegerField(verbose_name='Test Fees')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('blood_group', models.CharField(max_length=3, verbose_name='Blood Group')),
                ('chronic_disease', models.ManyToManyField(blank=True, null=True, to='health_profile.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50, verbose_name='Qualification')),
                ('fees', models.IntegerField(verbose_name='Consultaion Fees')),
                ('license_image', models.ImageField(upload_to='', verbose_name='Doctor License')),
                ('diseases', models.ManyToManyField(blank=True, null=True, to='health_profile.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
