# Generated by Django 4.1.3 on 2022-11-18 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbgTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('paco2', models.FloatField()),
                ('pao2', models.FloatField()),
                ('o2sat', models.FloatField(default=100.0)),
                ('hco3', models.FloatField()),
                ('na', models.FloatField()),
                ('cl', models.FloatField()),
                ('disorder', models.CharField(blank=True, max_length=50)),
                ('is_metabolic_acidosis', models.BooleanField(blank=True, default=False)),
                ('compensation', models.CharField(blank=True, max_length=30)),
                ('anion_gap', models.FloatField(blank=True)),
                ('delta_ratio', models.FloatField(blank=True)),
                ('anion_gap_result', models.CharField(blank=True, max_length=100)),
                ('delta_ratio_result', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
