# Generated by Django 4.1.3 on 2022-11-19 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copd', '0002_xraytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbgAutoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('paco2', models.FloatField()),
                ('pao2', models.FloatField()),
                ('o2sat', models.FloatField(default=100.0)),
                ('hco3', models.FloatField()),
                ('disorder', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
